### ISSUE TITLE
Utility for extracting CSV formatted writes

### ISSUE THREAD

**Issue by rhempel** [aselker/gameboy-sound-chip#1]
Is there a utility in place for extracting writes to the GB hardware registers when playing GBS files? In other words, do you know of a utility that can play a GBS file and create a CVS of the writes (with timestamps) for playback?

I am investigating making a lightweight GameBoy sound generator but would prefer not to have to also run the GB CU simulator on the micro :-)

In an ideal world, my program would be able to read a CSV stream of timestamped register contents, and use that to set up the virtual sound generator that way ...

**Comment by aselker** [comment]
That's not a bad idea!  I've never heard of one, though.

I don't think GameBoy emulators are very complicated, so I bet you could hack this functionality into an existing GBS player!  They probably have the representation you're looking for somewhere internally, you'd just have to dump it to a csv as it plays.

**Comment by rhempel** [comment]
Thanks for getting back to me - it turns out gbsplayer has the -o iodumper flag that does exactly what I want :-)

And I have already implemented a Gameboy audio ASIC on a cortex M4 CPU - it was fun ...

--
  Ralph Hempel
  ***@***.***

**Comment by jeremycryan** [comment]
Closing this issue because the "open issues" icon was stressing me out.
